name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Set up Docker
    #   uses: docker/setup-docker@v2
    #   with:
    #     dockerfile: Dockerfile
    #     context: .

    - name: Build Docker image
      run: docker build -t your-docker-image:latest .

    - name: Push Docker image to registry (optional)
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push your-docker-image:latest

    - name: Deploy to EC2
      run: |
        ssh -i ${{ secrets.SSH_PRIVATE_KEY_PATH }} ubuntu@your-ec2-public-ip 'bash -s' << 'ENDSSH'
          docker pull your-docker-image:latest
          docker stop your-container-name || true
          docker rm your-container-name || true
          docker run -d -p 80:80 --name your-container-name your-docker-image:latest
        ENDSSH
