name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag simpleci "${{ secrets.DOCKER_USERNAME }}/simpleci:latest"
        docker push "${{ secrets.DOCKER_USERNAME }}/newimage:latest

    - name: Build Docker Image
      run: docker build -t simpleapp .

    - name: Push Docker Image
      run: docker push simpleapp

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          # Commands to set up your environment on EC2 and deploy the Docker image
          ssh -o StrictHostKeyChecking=no -i /path/to/private/key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} 'docker pull your-docker-image-name'
          ssh -o StrictHostKeyChecking=no -i /path/to/private/key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} 'docker run -d -p 80:80 your-docker-image-name'
